version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.16

jobs:
  docker-job:
    docker:
      - image: circleci/node:12
      - image: localstack/localstack:0.10.5
        # will this apply to localstack, or just node?:
        environment:
          DEBUG: 1
          SERVICES: s3,iam,lambda

    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: foo
      AWS_ACCESS_KEY_ID: bar

    steps:
      - checkout

      - aws-cli/install

      - aws-cli/setup

      - install_terraform

      - run: env

      - run:
          name: Wait for localstack ports
          command: ./wait-for-localstack-ports.sh

      - run:
          name: aws stuff
          command: |
            aws --version
            aws --endpoint-url=http://localhost:4572 s3 mb s3://local-bucket
            aws --endpoint-url=http://localhost:4572 s3 ls

      - run:
          name: terraform
          command: |
            terraform init -input=false
            terraform apply -auto-approve -input=false

      - run:
          name: lambda
          command: |
            aws --endpoint-url=http://localhost:4574 lambda list-functions
          # If we try to invoke the lambda, we get this error:
          # localstack.services.awslambda.lambda_api.ClientError: Unable to find executor for Lambda function "ExampleLambda". Note that Node.js, Golang, and .Net Core Lambdas currently require LAMBDA_EXECUTOR=docker

  machine-job:
    machine:
      image: ubuntu-1604:201903-01

    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: foo
      AWS_ACCESS_KEY_ID: bar

    steps:
      - checkout

      - run:
          name: docker-compose up
          command: docker-compose up
          background: true
          environment:
            TMPDIR: ~/localstack
            DEBUG: 1

      - aws-cli/install

      - aws-cli/setup

      - install_terraform

      - run:
          name: Wait for localstack ports
          command: ./wait-for-localstack-ports.sh

      - run:
          name: Wait for localstack ready
          command: ./wait-for-localstack-ready.sh

      - run:
          name: aws stuff
          command: |
            aws --version
            aws --endpoint-url=http://localhost:4572 s3 mb s3://local-bucket
            aws --endpoint-url=http://localhost:4572 s3 ls

      - run:
          name: terraform
          command: |
            terraform init -input=false
            terraform apply -auto-approve -input=false

      - run:
          name: lambda
          command: |
            aws --endpoint-url=http://localhost:4574 lambda list-functions
            aws --endpoint-url=http://localhost:4574 lambda invoke --function-name ExampleLambda /dev/stdout

commands:
  install_terraform:
    description: "install terraform"
    steps:
      - run:
          name: Install Terraform
          environment:
            TF_VERSION: 0.12.18
          command: |
            mkdir -p ~/bin
            cd ~/bin
            wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
            unzip terraform_${TF_VERSION}_linux_amd64.zip
            echo 'export PATH=~/bin:$PATH'  >> $BASH_ENV
            terraform --version

workflows:
  version: 2
  jobs:
    jobs:
      - docker-job
      - machine-job