version: 2.1

jobs:
  docker-job:
    docker:
      - image: circleci/node:12
      # - image: debian:stretch

    steps:
      - checkout

      - run:
          name: docker commands
          command: |
            docker --version
            docker-compose --version
            docker run circleci/node:12 cat /etc/os-release
            docker run alpine cat /etc/alpine-release

  machine-job:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - run:
          name: docker commands
          command: |
            docker --version
            docker-compose --version
            docker run circleci/node:12 cat /etc/os-release
            docker run alpine cat /etc/alpine-release

workflows:
  version: 2
  jobs:
    jobs:
      - docker-job
      - machine-job